### ISSUE TITLE
Suggestion: Snellen, LogMar 

### ISSUE THREAD

**Issue by dharmeshmp** [muldjord/occurity#2]
Is it possible to add Snellen or LogMar charts by modifying this code?

Also some other features like the duochrome test.

**Comment by muldjord** [comment]
Occurity is designed in such a way that implementing new chart types is pretty straight-forward for anyone with Qt and C++ experience. Just inherit from the AbstractChart class and adjust accordingly to your needs.

The current scale used in Occurity is LogMar. We do not use Snellen anymore and as such I can only refer to my previous answer.
